sudo: required

language: cpp

compiler:
  - gcc
  - clang

arch:
  packages:
    - extra-cmake-modules
    - kdoctools
    - python
    - kitemmodels
    - kparts
    - kpty
    - libarchive
    - hicolor-icon-theme
    - p7zip
    - unzip
    - zip
    - lrzip
    # for GUI tests
    - xorg-server-xvfb
    # from AUR:
    - rar
    - unarchiver
  script:
    - "cmake -DCMAKE_BUILD_TYPE=Debug -DKDE_INSTALL_LIBDIR=lib -DKDE_INSTALL_USE_QT_SYS_PATHS=ON -DCMAKE_INSTALL_PREFIX=/usr ."
    - "make"
    - "sudo make install"
    # run the tests using the xvfb-run wrapper
    # https://bugzilla.redhat.com/show_bug.cgi?id=904851#c5 fixes 'libGL error: failed to load driver: swrast'
    - "xvfb-run -s \"-screen 0 640x480x24\" ctest --output-on-failure"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
